-- Unidades
INSERT INTO tb_unidade (nome) VALUES ('Matriz Central');
INSERT INTO tb_unidade(nome) VALUES ('Filial 1');
INSERT INTO tb_unidade(nome) VALUES ('Filial 2');
INSERT INTO tb_unidade (nome) VALUES ('Filial 3');
INSERT INTO tb_unidade (nome) VALUES ('Filial 4');


-- Endereços (relacionado a Unidade)
INSERT INTO tb_endereco (id, logradouro, complemento, numero, bairro, cep, cidade, uf) VALUES (1, 'Av. Paulista', 'Prédio 1', 1000, 'Centro', '01000-000', 'São Paulo', 1);
INSERT INTO tb_endereco (id, logradouro, complemento, numero, bairro, cep, cidade, uf) VALUES (2, 'Rua Rio Solimões', 'Quadra 10 lt 21', 170, 'Arroio da Manteiga', '093145-590', 'São Leopoldo', 21);
INSERT INTO tb_endereco (id, logradouro, complemento, numero, bairro, cep, cidade, uf) VALUES (3, 'Rua Vinte e Um de Abril', 'Quadra 89 lt 15', 1779, 'Mustardinha', '50760-375', 'Recife', 17);
INSERT INTO tb_endereco (id, logradouro, complemento, numero, bairro, cep, cidade, uf) VALUES (4, 'Av. Rio Branco', 'Sala 5', 200, 'Centro', '20040-000', 'Rio de Janeiro', 19);
INSERT INTO tb_endereco (id, logradouro, complemento, numero, bairro, cep, cidade, uf) VALUES (5, 'Rua Sete de Setembro', 'Prédio B', 150, 'Jardim América', '01415-000', 'São Paulo', 1);


-- Departamentos
INSERT INTO tb_departamento (nome, descricao, responsavel, localizacao, pertenceA_id) VALUES ('TI', 'Departamento de Tecnologia', 'Carlos Silva', 'Bloco A', 1);
INSERT INTO tb_departamento (nome, descricao, responsavel, localizacao, pertenceA_id) VALUES ('Financeiro', 'Departamento de Finanças', 'Joao Batista Bezerra', 'Bloco D', 2);
INSERT INTO tb_departamento (nome, descricao, responsavel, localizacao, pertenceA_id) VALUES ('Maketing', 'Departamento de comunicação e marketing', 'Maria das Graças Ferreira', 'Bloco C', 1);
INSERT INTO tb_departamento (nome, descricao, responsavel, localizacao, pertenceA_id) VALUES ('RH', 'Departamento de Recursos Humanos', 'Ana Paula Santos', 'Bloco B', 3);
INSERT INTO tb_departamento (nome, descricao, responsavel, localizacao, pertenceA_id) VALUES ('Vendas', 'Departamento de Vendas', 'Fernando Almeida', 'Bloco E', 4);


-- Funcionários
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('João Silva', 'https://img.com/joao.jpg', 'joao@email.com', '123.456.789-00', '(53) 98737-1386', 1, 'Desenvolvedor Back-end', 'Especialista em Java', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Maria Oliveira', 'https://img.com/maria.jpg', 'maria@email.com', '987.654.321-00', '(87) 98092-7924', 1, 'Analista de Dados', 'Especialista em PostgreSQL', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Carlos Eduardo Silva', 'https://img.com/carlos.jpg', 'carlos@email.com', '753.276.940-20', '(81) 2750-2633', 2, 'Analista Financeiro', 'Responsavel pela conciliação bancária e contas a receber', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Lorenna Feitosa Coelho', 'https://img.com/lorena.jpg', 'lorena@email.com', '782.181.110-69', '(53) 98737-1386', 1, 'Analista de Comunicação interna', 'Responsável pelo endo marketing', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Fernanda Lima', 'https://img.com/fernanda.jpg', 'fernanda@email.com', '312.456.789-01', '(21) 98765-4321', 1, 'Gerente de Projetos', 'Responsável por coordenação de projetos', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Ricardo Pereira', 'https://img.com/ricardo.jpg', 'ricardo@email.com', '654.321.987-02', '(11) 98765-0987', 1, 'Especialista em Segurança', 'Responsável por segurança da informação', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Ana Souza', 'https://img.com/ana.jpg', 'ana@email.com', '789.654.123-00', '(31) 98777-1234', 1, 'Desenvolvedora Front-end', 'Especialista em HTML, CSS e JavaScript, com experiência em frameworks como Angular e React', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Felipe Andrade', 'https://img.com/felipe.jpg', 'felipe@email.com', '456.789.123-00', '(21) 98767-1234', 1, 'Analista de Testes', 'Responsável por testes manuais e automatizados, garantindo a qualidade do software', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Juliana Ramos', 'https://img.com/juliana.jpg', 'juliana@email.com', '654.123.789-00', '(61) 98765-1234', 1, 'Engenheira de Software', 'Especialista em desenvolvimento de sistemas complexos, utilizando práticas de DevOps', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Gustavo Ferreira', 'https://img.com/gustavo.jpg', 'gustavo@email.com', '987.123.456-00', '(11) 98761-2345', 1, 'Designer UX/UI', 'Responsável pelo design de interfaces de usuário intuitivas e experiências de usuário otimizadas', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Camila Borges', 'https://img.com/camila.jpg', 'camila@email.com', '123.456.789-11', '(71) 98765-6789', 1, 'Analista de Marketing Digital', 'Especialista em estratégias de marketing digital, incluindo SEO e campanhas em redes sociais', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Rodrigo Menezes', 'https://img.com/rodrigo.jpg', 'rodrigo@email.com', '789.123.456-11', '(43) 98765-4321', 1, 'Engenheiro de Dados', 'Responsável pela arquitetura e manutenção de pipelines de dados, utilizando ferramentas como Apache Spark e Hadoop', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Patrícia Amaral', 'https://img.com/patricia.jpg', 'patricia@email.com', '456.789.123-11', '(34) 98765-5678', 1, 'Cientista de Dados', 'Especialista em análise de dados e criação de modelos preditivos utilizando Python e R', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Marcos Vinícius', 'https://img.com/marcos.jpg', 'marcos@email.com', '321.654.987-11', '(44) 98765-6789', 1, 'Administrador de Banco de Dados', 'Responsável pela gestão e otimização de bancos de dados, garantindo alta disponibilidade e desempenho', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Renata Barbosa', 'https://img.com/renata.jpg', 'renata@email.com', '987.654.321-11', '(19) 98765-7890', 1, 'Especialista em Redes', 'Responsável pela configuração e manutenção de redes corporativas, garantindo segurança e performance', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Lucas Almeida', 'https://img.com/lucas.jpg', 'lucas@email.com', '123.456.789-22', '(41) 98765-8910', 1, 'DevOps Engineer', 'Especialista em integração contínua e entrega contínua (CI/CD) utilizando ferramentas como Jenkins e Docker', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Larissa Mendes', 'https://img.com/larissa.jpg', 'larissa@email.com', '456.789.123-22', '(51) 98765-1234', 1, 'Especialista em Inteligência Artificial', 'Responsável pelo desenvolvimento de modelos de machine learning e deep learning', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Thiago Santos', 'https://img.com/thiago.jpg', 'thiago@email.com', '789.123.456-22', '(55) 98765-6789', 1, 'Gerente de TI', 'Responsável por gerenciar a infraestrutura de tecnologia da informação, incluindo servidores e redes', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Débora Silva', 'https://img.com/debora.jpg', 'debora@email.com', '321.654.987-22', '(85) 98765-7890', 1, 'Especialista em Desenvolvimento Mobile', 'Especialista em desenvolvimento de aplicativos para iOS e Android, utilizando Swift e Kotlin', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('André Gomes', 'https://img.com/andre.jpg', 'andre@email.com', '654.321.987-22', '(67) 98765-8910', 1, 'Arquiteto de Soluções', 'Responsável pelo design de arquiteturas de software escaláveis e eficientes', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Bianca Nunes', 'https://img.com/bianca.jpg', 'bianca@email.com', '987.123.456-33', '(32) 98765-1234', 1, 'Analista de Suporte', 'Responsável pelo suporte técnico a usuários finais, solucionando problemas e garantindo a continuidade dos serviços', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Júlio César', 'https://img.com/julio.jpg', 'julio@email.com', '123.456.789-33', '(95) 98765-5678', 1, 'Engenheiro de Software', 'Responsável pelo desenvolvimento de aplicações web escaláveis utilizando tecnologias modernas', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Vanessa Souza', 'https://img.com/vanessa.jpg', 'vanessa@email.com', '456.789.123-33', '(84) 98765-6789', 1, 'Gerente de Marketing', 'Responsável pelo planejamento e execução de estratégias de marketing, incluindo campanhas publicitárias', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Bruno Costa', 'https://img.com/bruno.jpg', 'bruno@email.com', '789.123.456-33', '(62) 98765-7890', 1, 'Desenvolvedor Full-stack', 'Especialista em desenvolvimento de aplicações web, desde o front-end até o back-end', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Alice Fernandes', 'https://img.com/alice.jpg', 'alice@email.com', '321.654.987-33', '(35) 98765-8910', 1, 'Analista de Infraestrutura', 'Responsável pela manutenção e otimização da infraestrutura de TI, incluindo servidores e redes', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Rafael Lima', 'https://img.com/rafael.jpg', 'rafael.lima@email.com', '654.321.987-33', '(47) 98765-1234', 1, 'Especialista em Cloud', 'Responsável pela migração e manutenção de sistemas em ambientes de computação em nuvem, utilizando AWS e Azure', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Fernando Reis', 'https://img.com/fernando.jpg', 'fernando.reis@email.com', '987.456.123-44', '(21) 98765-5678', 1, 'Analista de Sistemas', 'Responsável pela análise e desenvolvimento de sistemas, com experiência em UML e BPMN', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Cláudia Duarte', 'https://img.com/claudia.jpg', 'claudia.duarte@email.com', '123.654.987-44', '(31) 98765-6789', 1, 'Engenheira de Segurança', 'Especialista em segurança da informação, com certificação CISSP', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Rafael Moura', 'https://img.com/rafael.jpg', 'rafael.moura@email.com', '456.123.789-44', '(41) 98765-7890', 1, 'Administrador de Sistemas', 'Responsável pela gestão de servidores Linux e Windows, garantindo alta disponibilidade', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Gabriela Sousa', 'https://img.com/gabriela.jpg', 'gabriela.sousa@email.com', '789.456.123-44', '(71) 98765-8910', 1, 'Especialista em Big Data', 'Responsável pela análise de grandes volumes de dados, utilizando ferramentas como Hadoop e Spark', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Pedro Alves', 'https://img.com/pedro.jpg', 'pedro.alves@email.com', '123.789.456-44', '(51) 98765-1234', 1, 'Desenvolvedor iOS', 'Especialista em desenvolvimento de aplicativos para iOS, utilizando Swift', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Viviane Santos', 'https://img.com/viviane.jpg', 'viviane.santos@email.com', '456.789.123-55', '(61) 98765-5678', 1, 'Analista de RH', 'Responsável pelo recrutamento e seleção de novos talentos, além de treinamento e desenvolvimento', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Fábio Lima', 'https://img.com/fabio.jpg', 'fabio.lima@email.com', '789.123.456-55', '(81) 98765-6789', 1, 'Administrador de Redes', 'Especialista em configuração e manutenção de redes, com certificação CCNA', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Renata Costa', 'https://img.com/renata.jpg', 'renata.costa@email.com', '123.456.789-55', '(91) 98765-7890', 1, 'Desenvolvedora Android', 'Especialista em desenvolvimento de aplicativos para Android, utilizando Java e Kotlin', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Leonardo Ferreira', 'https://img.com/leonardo.jpg', 'leonardo.ferreira@email.com', '456.789.123-66', '(11) 98765-8910', 1, 'Gerente de Infraestrutura', 'Responsável pela gestão da infraestrutura de TI, garantindo a continuidade dos serviços e a segurança', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Isabela Martins', 'https://img.com/isabela.jpg', 'isabela.martins@email.com', '789.123.456-66', '(21) 98765-1234', 1, 'Analista de Segurança da Informação', 'Responsável por implementar políticas de segurança e realizar auditorias de segurança', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Rodrigo Silva', 'https://img.com/rodrigo.jpg', 'rodrigo.silva@email.com', '123.456.789-66', '(31) 98765-5678', 1, 'Gerente de Desenvolvimento', 'Responsável por coordenar a equipe de desenvolvimento, garantindo a entrega de projetos de software', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Tatiana Rocha', 'https://img.com/tatiana.jpg', 'tatiana.rocha@email.com', '456.789.123-77', '(41) 98765-6789', 1, 'Especialista em Testes Automatizados', 'Responsável por criar e manter scripts de testes automatizados, utilizando Selenium e JUnit', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Diego Costa', 'https://img.com/diego.jpg', 'diego.costa@email.com', '789.123.456-77', '(81) 98765-7890', 1, 'Engenheiro de DevOps', 'Especialista em automação de infraestrutura e processos de CI/CD, utilizando ferramentas como Ansible e Kubernetes', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Marcela Freitas', 'https://img.com/marcela.jpg', 'marcela.freitas@email.com', '123.456.789-77', '(91) 98765-8910', 1, 'Especialista em SEO', 'Responsável por otimizar o conteúdo digital para motores de busca, aumentando a visibilidade e o tráfego', 3);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Carlos Henrique', 'https://img.com/carlos.jpg', 'carlos.henrique@email.com', '456.789.123-88', '(51) 98765-1234', 1, 'Desenvolvedor PHP', 'Especialista em desenvolvimento de aplicações web utilizando PHP, com experiência em frameworks como Laravel', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Patrícia Almeida', 'https://img.com/patricia.jpg', 'patricia.almeida@email.com', '789.123.456-88', '(61) 98765-5678', 1, 'Especialista em Business Intelligence', 'Responsável por criar e manter soluções de BI, utilizando ferramentas como Power BI e Tableau', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Bruno Vieira', 'https://img.com/bruno.jpg', 'bruno.vieira@email.com', '123.456.789-88', '(71) 98765-6789', 1, 'Desenvolvedor Ruby', 'Especialista em desenvolvimento de aplicações web utilizando Ruby on Rails', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Daniela Mendes', 'https://img.com/daniela.jpg', 'daniela.mendes@email.com', '456.789.123-99', '(21) 98765-7890', 1, 'Analista de Negócios', 'Responsável por entender as necessidades dos clientes e propor soluções tecnológicas que atendam a essas necessidades', 2);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Luiz Felipe', 'https://img.com/luiz.jpg', 'luiz.felipe@email.com', '789.123.456-99', '(31) 98765-8910', 1, 'Desenvolvedor Python', 'Especialista em desenvolvimento de aplicações utilizando Python, com experiência em frameworks como Django e Flask', 1);
INSERT INTO tb_funcionario (nome, foto_url, email, cpf, telefone, status_funcionario, cargo, descricao, departamento_id) VALUES ('Mariana Costa', 'https://img.com/mariana.jpg', 'mariana.costa@email.com', '123.456.789-99', '(81) 98765-1234', 1, 'Gerente de Qualidade', 'Responsável por garantir a qualidade dos produtos e serviços entregues pela empresa, através de auditorias e melhorias contínuas', 3);




-- Equipes
INSERT INTO tb_equipe (nome, descricao, data_criacao) VALUES ('Equipe Backend', 'Responsável pela API', '2022-07-25T13:00:00Z');
INSERT INTO tb_equipe (nome, descricao, data_criacao) VALUES ('Equipe Dados', 'Análise de banco de dados', '2022-07-25T13:00:00Z');
INSERT INTO tb_equipe (nome, descricao, data_criacao) VALUES ('Equipe RH', 'Responsável por processos de RH', '2023-01-15T10:00:00Z');
INSERT INTO tb_equipe (nome, descricao, data_criacao) VALUES ('Equipe Vendas', 'Gestão de vendas e relacionamento com clientes', '2023-02-10T09:00:00Z');


-- Associando Funcionários a Equipes (Tabela Intermediária)
INSERT INTO tb_funcionario_equipe (funcionario_id, equipe_id) VALUES (1, 1);
INSERT INTO tb_funcionario_equipe (funcionario_id, equipe_id) VALUES (2, 2);
INSERT INTO tb_funcionario_equipe (funcionario_id, equipe_id) VALUES (3, 3);
INSERT INTO tb_funcionario_equipe (funcionario_id, equipe_id) VALUES (4, 4);


-- Projetos
INSERT INTO tb_projeto (nome, descricao, data_criacao, data_inicio, data_fim_previsto, data_fim_real, meta, risco, status_projeto, equipe_id) VALUES ('Sistema de Gestão', 'Plataforma para gerenciamento de processos', '2022-07-25T13:00:00Z', '2022-07-25T13:00:00Z', '2025-01-30', NULL, 'Entregar MVP em 3 meses', 1, 2, 1);
INSERT INTO tb_projeto (nome, descricao, data_criacao, data_inicio, data_fim_previsto, data_fim_real, meta, risco, status_projeto, equipe_id) VALUES ('Implementação de ERP', 'Implantação de sistema de ERP', '2023-03-01T08:00:00Z', '2023-03-01T08:00:00Z', '2024-03-01', NULL, 'Concluir implantação até o prazo', 2, 1, 2);


-- Tarefas
INSERT INTO tb_tarefa (nome, descricao, data_criacao, data_inicio, fim_previsto, fim_real, data_atualizacao, status_tarefa, projeto_id) VALUES ('Criar API', 'Desenvolver endpoints REST', '2022-07-25T13:00:00Z', '2022-07-25T13:00:00Z', '2024-12-15', NULL, NULL, 1, 1);
INSERT INTO tb_tarefa (nome, descricao, data_criacao, data_inicio, fim_previsto, fim_real, data_atualizacao, status_tarefa, projeto_id) VALUES ('Configurar módulos de ERP', 'Configurar módulos padrão do ERP', '2023-03-01T08:00:00Z', '2023-03-01T08:00:00Z', '2023-11-01', NULL, NULL, 3, 2);